import selectWhite from "./components/selectWhite";
import heroCards from "./components/heroCards";
import featuredCards from "./components/featuredCards";
import videoModal from "./components/videoModal";
import testimonialsCards from "./components/testimonialsCards";
import articles from "./components/articles";
import inputSelect from "./components/inputSelect";
import textArea from "./components/textArea";
import checkbox from "./components/checkbox";
import cookie from "./components/cookie";

selectWhite();
heroCards();
featuredCards();
videoModal();
testimonialsCards();
articles();
inputSelect();
textArea();
checkbox();
cookie();
